### ISSUE TITLE
Open program with `xdg-open` instead of `gnome-open`

### ISSUE THREAD

**Issue by Sliim** [PierreRambaud/groove-dl#4]
Hi! :)

You should open program with `xdg-open` instead of `gnome-open`. The advantage of `xdg-open` is that's desktop agnostic, `gnome-open` requires gnome's bin utils (`libgnome2-bin`) and looks to be replaced by `gvfs-open` in some linux distributions...

**Comment by PierreRambaud** [comment]
Thanks that was what I needed :)
