### ISSUE TITLE
destination folder not working for me from GUI

### ISSUE THREAD

**Issue by ivansabik** [PierreRambaud/groove-dl#6]
Hi, great app. Wanna report a bug, when using the GUI I choose a destination folder different from /tmp and it is displayed as selected however everything gets downloaded to /tmp folder anyway :S

I'm running ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]

**Comment by ivansabik** [comment]
Tried it three times more and it worked! :)
Dunno what I did wrong the first two

**Comment by PierreRambaud** [comment]
Hi and thanks for your feedback, I think you selected directory after adding songs in queue.
That not obvious in the UI but that's how it works :/

Regards

**Comment by ivansabik** [comment]
you're very welcome pierre I think it was due to that thing, I added and then changed the dir..
great work, i tried other scripts around and for me that's this is the only one working :)

**Comment by ivansabik** [comment]
I was also wondering, why did you switch to Ruby for this app.. just for fun? :P
Cuz I'm thinking of doing a script that aggregates downloaders for Soundcloud, Mixcloud, Grooveshark and Youtube but I'm still choosing between those two (python or ruby) and it would be helpful to know why

**Comment by PierreRambaud** [comment]
For real, it was just for fun. The first realease of this tool was written in Python, after I need to learn Ruby and Gtk, so I mixed them to rewrite this tool and some other tools (such as usblamp), more I needed to learn Ruby to better understand of Chef works.
For soundcloud, a Python tool: https://github.com/Sliim/soundcloud-syncer
There is no better language for scripting, just play with what you don't know or what you know, that depends on what you want to do :D

**Comment by ivansabik** [comment]
Great thanks for the feedback I think I'll go with python since is the one i'm more interested in getting to know better (until now I'm more a PHPer guy)... have a good one pierre
